- name: create directory to store nebula package on all machines in the cluster
  file:
    path: "{{ deploy_dir }}"
    state: directory
    mode: 0775

- name: verify if the binary is exist
  stat:
    path: "{{ deploy_dir }}/bin"
  register: stat_binary

- name: verify if the install package is exist
  stat:
    path: "{{ deploy_dir }}/{{ nebula_packages.name }}"
  register: stat_package

- name: copy nebula package from Control Machine to all machines in the cluster
  copy:
    src: "{{ packages_dir }}/{{ nebula_packages.name }}"
    dest: "{{ deploy_dir }}"
  when:
    -  not stat_package.stat.exists


- name: unzip rpm file
  shell: "{{ item }}"
  with_items:
    - "cd {{ deploy_dir }} && rpm2cpio {{ nebula_packages.name }} |cpio -div"
    - "mv {{ deploy_dir }}/usr/local/nebula/bin {{ deploy_dir }}/"
    - "mv {{ deploy_dir }}/usr/local/nebula/etc {{ deploy_dir }}/"
    - "mv {{ deploy_dir }}/usr/local/nebula/share {{ deploy_dir }}/"
    - "mv {{ deploy_dir }}/usr/local/nebula/scripts {{ deploy_dir }}/"

  when:
    -  not stat_binary.stat.exists 
    -  pkg == 'rpm'

- name: unzip tgz file
  shell: "{{ item }}"
  with_items:
    - "cd {{ deploy_dir }} && tar zxvf {{ nebula_packages.name }}"
    - "mv {{ deploy_dir }}/nebula-graph-{{ nebula_version }}.{{ os_version }}.{{ arc }}/bin {{ deploy_dir }}/"
    - "mv {{ deploy_dir }}/nebula-graph-{{ nebula_version }}.{{ os_version }}.{{ arc }}/etc {{ deploy_dir }}/"
    - "mv {{ deploy_dir }}/nebula-graph-{{ nebula_version }}.{{ os_version }}.{{ arc }}/share {{ deploy_dir }}/"
    - "mv {{ deploy_dir }}/nebula-graph-{{ nebula_version }}.{{ os_version }}.{{ arc }}/scripts {{ deploy_dir }}/"

  when:
    -  not stat_binary.stat.exists 
    -  pkg == 'tar.gz'
    
- name: config {{ module }}.conf
  template:
    src: "{{ playbook_dir}}/templates/{{ module }}.conf.j2"
    dest: "{{ deploy_dir }}/etc/{{ module }}.conf"
